# **Importing Libraries**

In [10]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sbn

## **Importing the Dataset**

In [3]:
data = pd.read_csv("/content/heart.csv")

## **Getting familiar with Dataset**

In [6]:
data.head()

Age Sex ChestPainType  ...  Oldpeak  ST_Slope  HeartDisease
0   40   M           ATA  ...      0.0        Up             0
1   49   F           NAP  ...      1.0      Flat             1
2   37   M           ATA  ...      0.0        Up             0
3   48   F           ASY  ...      1.5      Flat             1
4   54   M           NAP  ...      0.0        Up             0

[5 rows x 12 columns]

In [7]:
data.info()
data.shape
data.isna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Age             918 non-null    int64  
 1   Sex             918 non-null    object 
 2   ChestPainType   918 non-null    object 
 3   RestingBP       918 non-null    int64  
 4   Cholesterol     918 non-null    int64  
 5   FastingBS       918 non-null    int64  
 6   RestingECG      918 non-null    object 
 7   MaxHR           918 non-null    int64  
 8   ExerciseAngina  918 non-null    object 
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object 
 11  HeartDisease    918 non-null    int64  
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB


Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [9]:
data.describe()

Age   RestingBP  ...     Oldpeak  HeartDisease
count  918.000000  918.000000  ...  918.000000    918.000000
mean    53.510893  132.396514  ...    0.887364      0.553377
std      9.432617   18.514154  ...    1.066570      0.497414
min     28.000000    0.000000  ...   -2.600000      0.000000
25%     47.000000  120.000000  ...    0.000000      0.000000
50%     54.000000  130.000000  ...    0.600000      1.000000
75%     60.000000  140.000000  ...    1.500000      1.000000
max     77.000000  200.000000  ...    6.200000      1.000000

[8 rows x 7 columns]

## **Categorical Variable encoding**

In [15]:
from sklearn.preprocessing import OneHotEncoder
from sklearn import preprocessing

In [16]:
Sex = data.iloc[:,1:2].values
le = preprocessing.LabelEncoder()
Sex[:,0] = le.fit_transform(data.iloc[:,1:2])
Sex
ohe = preprocessing.OneHotEncoder()
Sex = ohe.fit_transform(Sex).toarray()
Sex

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[0., 1.],
       [1., 0.],
       [0., 1.],
       ...,
       [0., 1.],
       [1., 0.],
       [0., 1.]])

In [17]:
Sex = pd.DataFrame(data = Sex, index= range(918),columns=["Sex_M","Sex_F"])
Sex

Sex_M  Sex_F
0      0.0    1.0
1      1.0    0.0
2      0.0    1.0
3      1.0    0.0
4      0.0    1.0
..     ...    ...
913    0.0    1.0
914    0.0    1.0
915    0.0    1.0
916    1.0    0.0
917    0.0    1.0

[918 rows x 2 columns]

In [18]:
chest = data.iloc[:,2:3].values
le = preprocessing.LabelEncoder()
chest[:,0] = le.fit_transform(data.iloc[:,2:3])
chest
ohe = preprocessing.OneHotEncoder()
chest = ohe.fit_transform(chest).toarray()

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [19]:
chest = pd.DataFrame(data = chest, index= range(918),columns=["chest_ASY","chest_ATA","chest_NAP","chest_TA"])
chest

chest_ASY  chest_ATA  chest_NAP  chest_TA
0          0.0        1.0        0.0       0.0
1          0.0        0.0        1.0       0.0
2          0.0        1.0        0.0       0.0
3          1.0        0.0        0.0       0.0
4          0.0        0.0        1.0       0.0
..         ...        ...        ...       ...
913        0.0        0.0        0.0       1.0
914        1.0        0.0        0.0       0.0
915        1.0        0.0        0.0       0.0
916        0.0        1.0        0.0       0.0
917        0.0        0.0        1.0       0.0

[918 rows x 4 columns]

In [20]:
RestingECG = data.iloc[:,6:7].values
le = preprocessing.LabelEncoder()
RestingECG[:,0] = le.fit_transform(data.iloc[:,6:7])
RestingECG
ohe = preprocessing.OneHotEncoder()
RestingECG = ohe.fit_transform(RestingECG).toarray()

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [21]:
RestingECG = pd.DataFrame(data = RestingECG, index= range(918),columns=["RestingECG_LVH","RestingECG_Nor","RestingECG_ST"])
RestingECG

RestingECG_LVH  RestingECG_Nor  RestingECG_ST
0               0.0             1.0            0.0
1               0.0             1.0            0.0
2               0.0             0.0            1.0
3               0.0             1.0            0.0
4               0.0             1.0            0.0
..              ...             ...            ...
913             0.0             1.0            0.0
914             0.0             1.0            0.0
915             0.0             1.0            0.0
916             1.0             0.0            0.0
917             0.0             1.0            0.0

[918 rows x 3 columns]

In [22]:
ExerciseAngina = data.iloc[:,8:9].values
le = preprocessing.LabelEncoder()
ExerciseAngina[:,0] = le.fit_transform(data.iloc[:,8:9])
ExerciseAngina
ohe = preprocessing.OneHotEncoder()
ExerciseAngina = ohe.fit_transform(ExerciseAngina).toarray()

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [23]:
ExerciseAngina = pd.DataFrame(data = ExerciseAngina, index= range(918),columns=["ExerciseAngina_N","ExerciseAngina_Y"])
ExerciseAngina

ExerciseAngina_N  ExerciseAngina_Y
0                 1.0               0.0
1                 1.0               0.0
2                 1.0               0.0
3                 0.0               1.0
4                 1.0               0.0
..                ...               ...
913               1.0               0.0
914               1.0               0.0
915               0.0               1.0
916               1.0               0.0
917               1.0               0.0

[918 rows x 2 columns]

In [24]:
ST_Slope = data.iloc[:,10:11].values
le = preprocessing.LabelEncoder()
ST_Slope[:,0] = le.fit_transform(data.iloc[:,10:11])
ST_Slope
ohe = preprocessing.OneHotEncoder()
ST_Slope = ohe.fit_transform(ST_Slope).toarray()
ST_Slope

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       ...,
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
ST_Slope = pd.DataFrame(data = ST_Slope, index= range(918),columns=["ST_Slope_Down","ST_Slope_Flat","ST_Slope_up"])
ST_Slope

ST_Slope_Down  ST_Slope_Flat  ST_Slope_up
0              0.0            0.0          1.0
1              0.0            1.0          0.0
2              0.0            0.0          1.0
3              0.0            1.0          0.0
4              0.0            0.0          1.0
..             ...            ...          ...
913            0.0            1.0          0.0
914            0.0            1.0          0.0
915            0.0            1.0          0.0
916            0.0            1.0          0.0
917            0.0            0.0          1.0

[918 rows x 3 columns]

In [26]:
data.drop(["Sex", "ChestPainType", "RestingECG", "ExerciseAngina", "ST_Slope"], axis = 1, inplace = True)


In [27]:
data2 = pd.concat([Sex, chest, RestingECG, ExerciseAngina, ST_Slope],axis=1)

In [28]:
data2

Sex_M  Sex_F  chest_ASY  ...  ST_Slope_Down  ST_Slope_Flat  ST_Slope_up
0      0.0    1.0        0.0  ...            0.0            0.0          1.0
1      1.0    0.0        0.0  ...            0.0            1.0          0.0
2      0.0    1.0        0.0  ...            0.0            0.0          1.0
3      1.0    0.0        1.0  ...            0.0            1.0          0.0
4      0.0    1.0        0.0  ...            0.0            0.0          1.0
..     ...    ...        ...  ...            ...            ...          ...
913    0.0    1.0        0.0  ...            0.0            1.0          0.0
914    0.0    1.0        1.0  ...            0.0            1.0          0.0
915    0.0    1.0        1.0  ...            0.0            1.0          0.0
916    1.0    0.0        0.0  ...            0.0            1.0          0.0
917    0.0    1.0        0.0  ...            0.0            0.0          1.0

[918 rows x 14 columns]

In [29]:
data_up = pd.concat([data2,data],axis=1)

In [30]:
data_up

Sex_M  Sex_F  chest_ASY  ...  MaxHR  Oldpeak  HeartDisease
0      0.0    1.0        0.0  ...    172      0.0             0
1      1.0    0.0        0.0  ...    156      1.0             1
2      0.0    1.0        0.0  ...     98      0.0             0
3      1.0    0.0        1.0  ...    108      1.5             1
4      0.0    1.0        0.0  ...    122      0.0             0
..     ...    ...        ...  ...    ...      ...           ...
913    0.0    1.0        0.0  ...    132      1.2             1
914    0.0    1.0        1.0  ...    141      3.4             1
915    0.0    1.0        1.0  ...    115      1.2             1
916    1.0    0.0        0.0  ...    174      0.0             1
917    0.0    1.0        0.0  ...    173      0.0             0

[918 rows x 21 columns]

## **Splitting the data to create a model**

In [31]:
X = data_up.iloc[:,:-1].values
y = data_up.iloc[:,-1].values

In [32]:
print(X)
print(y)

[[  0.    1.    0.  ...   0.  172.    0. ]
 [  1.    0.    0.  ...   0.  156.    1. ]
 [  0.    1.    0.  ...   0.   98.    0. ]
 ...
 [  0.    1.    1.  ...   0.  115.    1.2]
 [  1.    0.    0.  ...   0.  174.    0. ]
 [  0.    1.    0.  ...   0.  173.    0. ]]
[0 1 0 1 0 0 0 0 1 0 0 1 0 1 0 0 1 0 1 1 0 0 0 1 0 0 0 0 0 0 1 0 1 1 0 0 1
 0 0 0 0 1 0 0 1 0 0 0 0 1 1 1 0 0 0 0 1 1 0 1 0 0 0 1 0 0 0 0 1 0 1 0 1 0
 1 0 1 0 0 1 0 0 1 0 1 1 1 0 1 0 0 0 0 1 0 1 0 0 0 0 1 0 1 1 1 0 0 0 0 0 0
 1 0 0 0 1 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0 1 1 1 0 1 0 0 1 1 1 1 1 0 1 0 0 0
 0 1 0 0 0 0 0 1 1 0 1 0 1 1 0 0 0 1 1 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 1 0 0
 1 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 1 1 0 0 1 0 1 0 0 0 1 1
 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 1 1 1 0 1 1 0 1 0 1 1 1 1 1 1 0 0 1 0 0 0 0
 0 0 0 1 1 1 0 1 0 1 0 0 0 1 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 1
 1 1 1 1 1 0 1 1 1 1 1 0 1 1 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0
 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [35]:
sc = preprocessing.StandardScaler()

In [36]:
X_train=sc.fit_transform(X_train)
X_test =sc.fit_transform(X_test)

## **Logistic Regression to predict heart disease**

In [37]:
from sklearn.linear_model import LogisticRegression

In [38]:
LR = LogisticRegression()

In [39]:
LR.fit(X_train,y_train)

LogisticRegression()

In [40]:
lp = LR.predict(X_test)

In [41]:
lp

array([1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1])

In [42]:
from sklearn.metrics import confusion_matrix

In [43]:
mat = confusion_matrix(y_test,lp)
mat

array([[67, 18],
       [ 8, 91]])

In [44]:
from sklearn.metrics import classification_report
cr=classification_report(y_test,lp,labels=[1,0])
print(cr)

              precision    recall  f1-score   support

           1       0.83      0.92      0.88        99
           0       0.89      0.79      0.84        85

    accuracy                           0.86       184
   macro avg       0.86      0.85      0.86       184
weighted avg       0.86      0.86      0.86       184



## **Decision Tree to predict Heart Disease**

In [45]:
from sklearn.tree import DecisionTreeClassifier

In [46]:
DC = DecisionTreeClassifier()

In [47]:
DC.fit(X_train,y_train)

DecisionTreeClassifier()

In [48]:
DP = DC.predict(X_test)

In [49]:
mat_dc = confusion_matrix(y_test,DP)
mat_dc

array([[64, 21],
       [26, 73]])

In [50]:
cr_dc=classification_report(y_test,DP,labels=[1,0])
print(cr_dc)

              precision    recall  f1-score   support

           1       0.78      0.74      0.76        99
           0       0.71      0.75      0.73        85

    accuracy                           0.74       184
   macro avg       0.74      0.75      0.74       184
weighted avg       0.75      0.74      0.74       184



In [51]:
from sklearn.ensemble import AdaBoostClassifier

In [52]:
Aboost = AdaBoostClassifier(DecisionTreeClassifier(),n_estimators=5,learning_rate=0.5)

In [53]:
Aboost.fit(X_train,y_train)

AdaBoostClassifier(base_estimator=DecisionTreeClassifier(), learning_rate=0.5,
                   n_estimators=5)

In [54]:
Ap = Aboost.predict(X_test)

In [55]:
cr_Ap=classification_report(y_test,Ap,labels=[1,0])
print(cr_Ap)

              precision    recall  f1-score   support

           1       0.81      0.81      0.81        99
           0       0.78      0.78      0.78        85

    accuracy                           0.79       184
   macro avg       0.79      0.79      0.79       184
weighted avg       0.79      0.79      0.79       184

